apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: {{ template "guestbookchannel.fullname" . }}-redisslave
  annotations:
    app.ibm.com/is-local-deployable: "false"
  labels:
    app: {{ template "guestbookchannel.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: {{ template "guestbookchannel.fullname" . }}-redisslave
    spec:
      selector:
        matchLabels:
          app: {{ template "guestbookchannel.name" . }}
          release: {{ .Release.Name }}
          role: slave
          tier: backend
      replicas: 1
      template:
        metadata:
          labels:
            app: {{ template "guestbookchannel.name" . }}
            release: {{ .Release.Name }}
            role: slave
            tier: backend
        spec:
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.redisslave.deployment.repository }}:{{ .Values.redisslave.deployment.tag }}"
            imagePullPolicy: {{ .Values.redisslave.deployment.pullPolicy }}
            ports:
              - containerPort: 6379
            env:
            - name: GET_HOSTS_FROM
              value: dns
---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: {{ template "guestbookchannel.fullname" . }}-redisslaveservice
  annotations:
    app.ibm.com/is-local-deployable: "false"
  labels:
    app: {{ template "guestbookchannel.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    kind: Service
    apiVersion: v1
    metadata:
      name: redis-slave
    spec:
      type: {{ .Values.redisslave.service.type }}
      ports:
        - port: 6379
      selector:
        app: {{ template "guestbookchannel.name" . }}
        release: {{ .Release.Name }}
        role: slave
        tier: backend
